export const mockMyTags = [
  { tagId: 1, tagName: 'Twitter' },
  { tagId: 2, tagName: 'Facebook' },
  { tagId: 3, tagName: 'Top 10' },
  { tagId: 4, tagName: 'Test' },
  { tagId: 5, tagName: 'ToDo' },
]

export const mockCommunityTags = [
  { tagId: 1, tagName: 'Top 100' },
  { tagId: 2, tagName: 'Finances' },
  { tagId: 3, tagName: 'Media' },
  { tagId: 4, tagName: 'Favourites' },
]

export const mockDapplets = [
  {
    dappletId: 1,
    logo: '/public/mockData/logos/dyson.svg',
    name: 'Ethereum Contracts Example',
    date: 1691942217,
    shortDesc: 'Feature adds tweets to Ethereum contract',
    fullDesc:
      'Semper neque leo scelerisque gravida pharetra, elit viverra varius. Leo et pretium massa tristique mauris habitasse in in. Et cras sociis tellus viverra at dictumst quisque praesent arcu. Eu faucibus id at odio praesent. Ut nibh porta ipsum in eget id netus pharetra in. Ultrices scelerisque augue dui eget lacus, aenean cursus in. Consequat rhoncus egestas ultricies imperdiet diam. Imperdiet mollis egestas est faucibus sit tristique eu.',
    appOwner: 'debra.holt',
    communityTags: [
      { tagId: 1, tagName: 'Top 100' },
      { tagId: 2, tagName: 'Social' },
    ],
    semperNeque: 'Amet, porttitor gravida id',
    aliquam: 'Viverra dictum arcu.',
    urna: 'Ultrices pellentesque.',
    leoIpsum: 'Vulputate dolor nam in.',
    inEuismod: 'Felis pretium neque.',
    namDiam: 'Elit accumsan leo non.',
    elitSagittis: 'Ut molestie eros.',
    justoAmet: 'Nullam nec ultrices.',
  },
  {
    dappletId: 2,
    logo: '/public/mockData/logos/bmw.svg',
    name: 'Habitant sollicitudin velit',
    date: 1691942217,
    shortDesc: 'Feature adds tweets to Ethereum contract',
    fullDesc:
      'Semper neque leo scelerisque gravida pharetra, elit viverra varius. Leo et pretium massa tristique mauris habitasse in in. Et cras sociis tellus viverra at dictumst quisque praesent arcu. Eu faucibus id at odio praesent. Ut nibh porta ipsum in eget id netus pharetra in. Ultrices scelerisque augue dui eget lacus, aenean cursus in. Consequat rhoncus egestas ultricies imperdiet diam. Imperdiet mollis egestas est faucibus sit tristique eu.',
    appOwner: 'michael.mitc',
    communityTags: [
      { tagId: 2, tagName: 'Social' },
      { tagId: 4, tagName: 'Favourites' },
    ],
    semperNeque: 'Amet, porttitor gravida id',
    aliquam: 'Viverra dictum arcu.',
    urna: 'Ultrices pellentesque.',
    leoIpsum: 'Vulputate dolor nam in.',
    inEuismod: 'Felis pretium neque.',
    namDiam: 'Elit accumsan leo non.',
    elitSagittis: 'Ut molestie eros.',
    justoAmet: 'Nullam nec ultrices.',
  },
  {
    dappletId: 3,
    logo: '/public/mockData/logos/dyson.svg',
    name: 'Ethereum Contracts Example',
    date: 1691942217,
    shortDesc: 'Feature adds tweets to Ethereum contract',
    fullDesc:
      'Semper neque leo scelerisque gravida pharetra, elit viverra varius. Leo et pretium massa tristique mauris habitasse in in. Et cras sociis tellus viverra at dictumst quisque praesent arcu. Eu faucibus id at odio praesent. Ut nibh porta ipsum in eget id netus pharetra in. Ultrices scelerisque augue dui eget lacus, aenean cursus in. Consequat rhoncus egestas ultricies imperdiet diam. Imperdiet mollis egestas est faucibus sit tristique eu.',
    appOwner: 'sara.cruz',
    communityTags: [
      { tagId: 1, tagName: 'Top 100' },
      { tagId: 2, tagName: 'Social' },
    ],
    semperNeque: 'Amet, porttitor gravida id',
    aliquam: 'Viverra dictum arcu.',
    urna: 'Ultrices pellentesque.',
    leoIpsum: 'Vulputate dolor nam in.',
    inEuismod: 'Felis pretium neque.',
    namDiam: 'Elit accumsan leo non.',
    elitSagittis: 'Ut molestie eros.',
    justoAmet: 'Nullam nec ultrices.',
  },
  {
    dappletId: 4,
    logo: '/public/mockData/logos/bmw.svg',
    name: 'Habitant sollicitudin velit',
    date: 1691942217,
    shortDesc: 'Feature adds tweets to Ethereum contract',
    fullDesc:
      'Semper neque leo scelerisque gravida pharetra, elit viverra varius. Leo et pretium massa tristique mauris habitasse in in. Et cras sociis tellus viverra at dictumst quisque praesent arcu. Eu faucibus id at odio praesent. Ut nibh porta ipsum in eget id netus pharetra in. Ultrices scelerisque augue dui eget lacus, aenean cursus in. Consequat rhoncus egestas ultricies imperdiet diam. Imperdiet mollis egestas est faucibus sit tristique eu.',
    appOwner: 'jessica.hanson',
    communityTags: [
      { tagId: 2, tagName: 'Social' },
      { tagId: 4, tagName: 'Favourites' },
    ],
    semperNeque: 'Amet, porttitor gravida id',
    aliquam: 'Viverra dictum arcu.',
    urna: 'Ultrices pellentesque.',
    leoIpsum: 'Vulputate dolor nam in.',
    inEuismod: 'Felis pretium neque.',
    namDiam: 'Elit accumsan leo non.',
    elitSagittis: 'Ut molestie eros.',
    justoAmet: 'Nullam nec ultrices.',
  },
  {
    dappletId: 5,
    logo: '/public/mockData/logos/dyson.svg',
    name: 'Ethereum Contracts Example',
    date: 1691942217,
    shortDesc: 'Feature adds tweets to Ethereum contract',
    fullDesc:
      'Semper neque leo scelerisque gravida pharetra, elit viverra varius. Leo et pretium massa tristique mauris habitasse in in. Et cras sociis tellus viverra at dictumst quisque praesent arcu. Eu faucibus id at odio praesent. Ut nibh porta ipsum in eget id netus pharetra in. Ultrices scelerisque augue dui eget lacus, aenean cursus in. Consequat rhoncus egestas ultricies imperdiet diam. Imperdiet mollis egestas est faucibus sit tristique eu.',
    appOwner: 'debra.holt',
    communityTags: [
      { tagId: 1, tagName: 'Top 100' },
      { tagId: 2, tagName: 'Social' },
    ],
    semperNeque: 'Amet, porttitor gravida id',
    aliquam: 'Viverra dictum arcu.',
    urna: 'Ultrices pellentesque.',
    leoIpsum: 'Vulputate dolor nam in.',
    inEuismod: 'Felis pretium neque.',
    namDiam: 'Elit accumsan leo non.',
    elitSagittis: 'Ut molestie eros.',
    justoAmet: 'Nullam nec ultrices.',
  },
  {
    dappletId: 6,
    logo: '/public/mockData/logos/bmw.svg',
    name: 'Habitant sollicitudin velit',
    date: 1691942217,
    shortDesc: 'Feature adds tweets to Ethereum contract',
    fullDesc:
      'Semper neque leo scelerisque gravida pharetra, elit viverra varius. Leo et pretium massa tristique mauris habitasse in in. Et cras sociis tellus viverra at dictumst quisque praesent arcu. Eu faucibus id at odio praesent. Ut nibh porta ipsum in eget id netus pharetra in. Ultrices scelerisque augue dui eget lacus, aenean cursus in. Consequat rhoncus egestas ultricies imperdiet diam. Imperdiet mollis egestas est faucibus sit tristique eu.',
    appOwner: 'michael.mitc',
    communityTags: [
      { tagId: 2, tagName: 'Social' },
      { tagId: 4, tagName: 'Favourites' },
    ],
    semperNeque: 'Amet, porttitor gravida id',
    aliquam: 'Viverra dictum arcu.',
    urna: 'Ultrices pellentesque.',
    leoIpsum: 'Vulputate dolor nam in.',
    inEuismod: 'Felis pretium neque.',
    namDiam: 'Elit accumsan leo non.',
    elitSagittis: 'Ut molestie eros.',
    justoAmet: 'Nullam nec ultrices.',
  },
  {
    dappletId: 7,
    logo: '/public/mockData/logos/dyson.svg',
    name: 'Ethereum Contracts Example',
    date: 1691942217,
    shortDesc: 'Feature adds tweets to Ethereum contract',
    fullDesc:
      'Semper neque leo scelerisque gravida pharetra, elit viverra varius. Leo et pretium massa tristique mauris habitasse in in. Et cras sociis tellus viverra at dictumst quisque praesent arcu. Eu faucibus id at odio praesent. Ut nibh porta ipsum in eget id netus pharetra in. Ultrices scelerisque augue dui eget lacus, aenean cursus in. Consequat rhoncus egestas ultricies imperdiet diam. Imperdiet mollis egestas est faucibus sit tristique eu.',
    appOwner: 'sara.cruz',
    communityTags: [
      { tagId: 1, tagName: 'Top 100' },
      { tagId: 2, tagName: 'Social' },
    ],
    semperNeque: 'Amet, porttitor gravida id',
    aliquam: 'Viverra dictum arcu.',
    urna: 'Ultrices pellentesque.',
    leoIpsum: 'Vulputate dolor nam in.',
    inEuismod: 'Felis pretium neque.',
    namDiam: 'Elit accumsan leo non.',
    elitSagittis: 'Ut molestie eros.',
    justoAmet: 'Nullam nec ultrices.',
  },
  {
    dappletId: 8,
    logo: '/public/mockData/logos/bmw.svg',
    name: 'Habitant sollicitudin velit',
    date: 1691942217,
    shortDesc: 'Feature adds tweets to Ethereum contract',
    fullDesc:
      'Semper neque leo scelerisque gravida pharetra, elit viverra varius. Leo et pretium massa tristique mauris habitasse in in. Et cras sociis tellus viverra at dictumst quisque praesent arcu. Eu faucibus id at odio praesent. Ut nibh porta ipsum in eget id netus pharetra in. Ultrices scelerisque augue dui eget lacus, aenean cursus in. Consequat rhoncus egestas ultricies imperdiet diam. Imperdiet mollis egestas est faucibus sit tristique eu.',
    appOwner: 'jessica.hanson',
    communityTags: [
      { tagId: 2, tagName: 'Social' },
      { tagId: 4, tagName: 'Favourites' },
    ],
    semperNeque: 'Amet, porttitor gravida id',
    aliquam: 'Viverra dictum arcu.',
    urna: 'Ultrices pellentesque.',
    leoIpsum: 'Vulputate dolor nam in.',
    inEuismod: 'Felis pretium neque.',
    namDiam: 'Elit accumsan leo non.',
    elitSagittis: 'Ut molestie eros.',
    justoAmet: 'Nullam nec ultrices.',
  },
  {
    dappletId: 9,
    logo: '/public/mockData/logos/dyson.svg',
    name: 'Ethereum Contracts Example',
    date: 1691942217,
    shortDesc: 'Feature adds tweets to Ethereum contract',
    fullDesc:
      'Semper neque leo scelerisque gravida pharetra, elit viverra varius. Leo et pretium massa tristique mauris habitasse in in. Et cras sociis tellus viverra at dictumst quisque praesent arcu. Eu faucibus id at odio praesent. Ut nibh porta ipsum in eget id netus pharetra in. Ultrices scelerisque augue dui eget lacus, aenean cursus in. Consequat rhoncus egestas ultricies imperdiet diam. Imperdiet mollis egestas est faucibus sit tristique eu.',
    appOwner: 'debra.holt',
    communityTags: [
      { tagId: 1, tagName: 'Top 100' },
      { tagId: 2, tagName: 'Social' },
    ],
    semperNeque: 'Amet, porttitor gravida id',
    aliquam: 'Viverra dictum arcu.',
    urna: 'Ultrices pellentesque.',
    leoIpsum: 'Vulputate dolor nam in.',
    inEuismod: 'Felis pretium neque.',
    namDiam: 'Elit accumsan leo non.',
    elitSagittis: 'Ut molestie eros.',
    justoAmet: 'Nullam nec ultrices.',
  },
  {
    dappletId: 10,
    logo: '/public/mockData/logos/bmw.svg',
    name: 'Habitant sollicitudin velit',
    date: 1691942217,
    shortDesc: 'Feature adds tweets to Ethereum contract',
    fullDesc:
      'Semper neque leo scelerisque gravida pharetra, elit viverra varius. Leo et pretium massa tristique mauris habitasse in in. Et cras sociis tellus viverra at dictumst quisque praesent arcu. Eu faucibus id at odio praesent. Ut nibh porta ipsum in eget id netus pharetra in. Ultrices scelerisque augue dui eget lacus, aenean cursus in. Consequat rhoncus egestas ultricies imperdiet diam. Imperdiet mollis egestas est faucibus sit tristique eu.',
    appOwner: 'michael.mitc',
    communityTags: [
      { tagId: 2, tagName: 'Social' },
      { tagId: 4, tagName: 'Favourites' },
    ],
    semperNeque: 'Amet, porttitor gravida id',
    aliquam: 'Viverra dictum arcu.',
    urna: 'Ultrices pellentesque.',
    leoIpsum: 'Vulputate dolor nam in.',
    inEuismod: 'Felis pretium neque.',
    namDiam: 'Elit accumsan leo non.',
    elitSagittis: 'Ut molestie eros.',
    justoAmet: 'Nullam nec ultrices.',
  },
  {
    dappletId: 11,
    logo: '/public/mockData/logos/dyson.svg',
    name: 'Ethereum Contracts Example',
    date: 1691942217,
    shortDesc: 'Feature adds tweets to Ethereum contract',
    fullDesc:
      'Semper neque leo scelerisque gravida pharetra, elit viverra varius. Leo et pretium massa tristique mauris habitasse in in. Et cras sociis tellus viverra at dictumst quisque praesent arcu. Eu faucibus id at odio praesent. Ut nibh porta ipsum in eget id netus pharetra in. Ultrices scelerisque augue dui eget lacus, aenean cursus in. Consequat rhoncus egestas ultricies imperdiet diam. Imperdiet mollis egestas est faucibus sit tristique eu.',
    appOwner: 'sara.cruz',
    communityTags: [
      { tagId: 1, tagName: 'Top 100' },
      { tagId: 2, tagName: 'Social' },
    ],
    semperNeque: 'Amet, porttitor gravida id',
    aliquam: 'Viverra dictum arcu.',
    urna: 'Ultrices pellentesque.',
    leoIpsum: 'Vulputate dolor nam in.',
    inEuismod: 'Felis pretium neque.',
    namDiam: 'Elit accumsan leo non.',
    elitSagittis: 'Ut molestie eros.',
    justoAmet: 'Nullam nec ultrices.',
  },
  {
    dappletId: 12,
    logo: '/public/mockData/logos/bmw.svg',
    name: 'Habitant sollicitudin velit',
    date: 1691942217,
    shortDesc: 'Feature adds tweets to Ethereum contract',
    fullDesc:
      'Semper neque leo scelerisque gravida pharetra, elit viverra varius. Leo et pretium massa tristique mauris habitasse in in. Et cras sociis tellus viverra at dictumst quisque praesent arcu. Eu faucibus id at odio praesent. Ut nibh porta ipsum in eget id netus pharetra in. Ultrices scelerisque augue dui eget lacus, aenean cursus in. Consequat rhoncus egestas ultricies imperdiet diam. Imperdiet mollis egestas est faucibus sit tristique eu.',
    appOwner: 'jessica.hanson',
    communityTags: [
      { tagId: 2, tagName: 'Social' },
      { tagId: 4, tagName: 'Favourites' },
    ],
    semperNeque: 'Amet, porttitor gravida id',
    aliquam: 'Viverra dictum arcu.',
    urna: 'Ultrices pellentesque.',
    leoIpsum: 'Vulputate dolor nam in.',
    inEuismod: 'Felis pretium neque.',
    namDiam: 'Elit accumsan leo non.',
    elitSagittis: 'Ut molestie eros.',
    justoAmet: 'Nullam nec ultrices.',
  },
  {
    dappletId: 13,
    logo: '/public/mockData/logos/dyson.svg',
    name: 'Ethereum Contracts Example',
    date: 1691942217,
    shortDesc: 'Feature adds tweets to Ethereum contract',
    fullDesc:
      'Semper neque leo scelerisque gravida pharetra, elit viverra varius. Leo et pretium massa tristique mauris habitasse in in. Et cras sociis tellus viverra at dictumst quisque praesent arcu. Eu faucibus id at odio praesent. Ut nibh porta ipsum in eget id netus pharetra in. Ultrices scelerisque augue dui eget lacus, aenean cursus in. Consequat rhoncus egestas ultricies imperdiet diam. Imperdiet mollis egestas est faucibus sit tristique eu.',
    appOwner: 'sara.cruz',
    communityTags: [
      { tagId: 1, tagName: 'Top 100' },
      { tagId: 2, tagName: 'Social' },
    ],
    semperNeque: 'Amet, porttitor gravida id',
    aliquam: 'Viverra dictum arcu.',
    urna: 'Ultrices pellentesque.',
    leoIpsum: 'Vulputate dolor nam in.',
    inEuismod: 'Felis pretium neque.',
    namDiam: 'Elit accumsan leo non.',
    elitSagittis: 'Ut molestie eros.',
    justoAmet: 'Nullam nec ultrices.',
  },
]

export const mockMyDapplets = [
  {
    dappletId: 1,
    userTags: [
      { tagId: 1, tagName: 'Twitter' },
      { tagId: 5, tagName: 'ToDo' },
    ],
    dappletState: true,
  },

  {
    dappletId: 4,
    userTags: [
      { tagId: 1, tagName: 'Twitter' },
      { tagId: 2, tagName: 'Facebook' },
    ],
    dappletState: false,
  },

  {
    dappletId: 6,
    userTags: [
      { tagId: 1, tagName: 'Twitter' },
      { tagId: 4, tagName: 'Test' },
      { tagId: 5, tagName: 'ToDo' },
    ],
    dappletState: true,
  },
]
